name: Generator Test (Linux)

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  generator-testing-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Pnpm
        run: corepack enable

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Set Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Test MWA
        run: LOCAL=true SIMPLE=true pnpm --filter ./tests run test:mwa

      - name: Test Module
        run: LOCAL=true SIMPLE=true pnpm --filter ./tests run test:module

      - name: Test Monorepo
        run: LOCAL=true SIMPLE=true pnpm --filter ./tests run test:monorepo
